const base = [
	{
		id: 0,
		title: '',
		artist: '',
		cover: -1,
		media: '',
		duration: 0,
	},
	{
		id: 1,
		title: 'Утро которым мы умрём',
		artist: 'Mujuice',
		cover: 4,
		media: 'Утро которым мы умрём   Mujuice.mp3',
		duration: 257.044898,
	},
	{
		id: 2,
		title: 'Love Will Tear Apart',
		artist: 'Alicia Widar',
		cover: 0,
		media: 'widar_love.mp3',
		duration: 165.433469,
	},
	{
		id: 3,
		title: 'August',
		artist: 'Intelligency',
		cover: 17,
		media: 'August   Intelligency.mp3',
		duration: 207.386122,
	},
	{
		id: 4,
		title: 'Use Me',
		artist: 'Alec Benjamin',
		cover: 5,
		media: 'Nightcore - Use me (Lyrics) (320 kbps).mp3',
		duration: 147.6512,
	},
	{
		id: 5,
		title: 'Первый снег',
		artist: 'Сова',
		cover: 9,
		media: 'Первый снег   Сова.mp3',
		duration: 178.599184,
	},
	{
		id: 6,
		title: 'Моя',
		artist: 'kameraxstyle',
		cover: 1,
		media: 'kameraxstyle_moya.mp3',
		duration: 135.68,
	},
	{
		id: 7,
		title: 'Гагарин, я вас любила',
		artist: 'Ундервуд',
		cover: 11,
		media: 'Гагарин_я_вас_любила_Избранное_Ундервуд.m4a',
		duration: 247.27,
	},
	{
		id: 8,
		title: 'Крайности',
		artist: 'Кладбище Черновиков',
		cover: 2,
		media: 'kch_krainosti.mp3',
		duration: 74.057143,
	},
	{
		id: 9,
		title: 'Sleepwalker',
		artist: 'Illenium',
		cover: 13,
		media: 'Sleepwalker   Illenium.mp3',
		duration: 250.226939,
	},
	{
		id: 10,
		title: 'Твоего балкона свет!',
		artist: 'Пупок Комсомола',
		cover: 3,
		media: 'komsomola_svet.mp3',
		duration: 143.595102,
	},
	{
		id: 11,
		title: 'Abstract nonsense',
		artist: 'Kagamine Rin',
		cover: 15,
		media: 'Abstract nonsense   Kagamine Rin.mp3',
		duration: 237.55755,
	},
	{
		id: 12,
		title: 'За углом',
		artist: 'Пустецкий',
		cover: 18,
		media: 'pustetskiy_uglom.mp3',
		duration: 107.52,
	},
	{
		id: 13,
		title: 'Никотиновая доза',
		artist: 'СуШ(07)',
		cover: 19,
		media: 'sush_doza.mp3',
		duration: 118.93551,
	},
	{
		id: 14,
		title: 'Мутные пятна',
		artist: 'nutakoe',
		cover: 14,
		media: 'nutakoe_pyatna.mp3',
		duration: 107.337125,
	},
	{
		id: 15,
		title: 'Pieces',
		artist: 'Sum 41',
		cover: 12,
		media: 'Pieces   Sum 41.mp3',
		duration: 182.073469,
	},
	{
		id: 16,
		title: 'Ever Fallen In Love',
		artist: 'Buzzcocks',
		cover: 7,
		media: 'Buzzcocks-Ever_Fallen_In_Love.mp3',
		duration: 172.852225,
	},
	{
		id: 17,
		title: 'I Dont Care Anymore',
		artist: 'Cathedral Bells',
		cover: 10,
		media: 'Cathedral Bells - I Dont Care Anymo... - V3H.mp3',
		duration: 290.586122,
	},
	{
		id: 18,
		title: 'Я знаю твой телефон',
		artist: 'akaky',
		cover: 6,
		media: 'Я знаю твой телефон - akaky.m4a',
		duration: 157.967,
	},
	{
		id: 19,
		title: 'Плачущий Блаженный',
		artist: 'miltei',
		cover: 16,
		media: 'плачущий_блаженный_cover_сияние_72_катя_милтей.mp3',
		duration: 141.897143,
	},
	{
		id: 20,
		title: 'Взгляд с экрана',
		artist: 'Наутилус Помпилиус',
		cover: 8,
		media: 'Взгляд_с_экрана_Наутилус_Помпилиус.mp3',
		duration: 262.661224,
	},
];